font_family      MesloLGS NF
font_size 15.0

background #24283b
foreground #a9b1d6

# Keybindings
map super+shift+equal change_font_size all +2.0
map super+shift+minus change_font_size all -2.0
map ctrl+shift+equal
map ctrl+shift+minus

background_opacity 0.8
confirm_os_window_close 0

# Cursor
cursor_trail 10 
cursor_trail_decay 0.1 0.3
cursor_trail_start_threshold 0 
