 [mgr]
 prepend_keymap = [
     {on = ["t", "3"], run = 'shell -- /usr/local/bin/tomp3 "$@"', desc = "Convert to mp3"},
     {on = ["t", "4"], run = 'shell -- /usr/local/bin/tomp4 "$@"', desc = "Convert to mp4"},
     { on = "q", run = "null", desc = "Do not quit the process"},
     { on = "<C-q>", run = "quit", desc = "Quit the process"},
 ]
