 [mgr]
 prepend_keymap = [
     {on = ["t", "m"], run = 'shell -- /usr/local/bin/tomp3 "$@"', desc = "Convert to mp3"},
     { on = "<C-q>", run = "quit", desc = "Quit the process"},
     { on = "q", run = "null", desc = "Do not quit the process"},

 ]
